---
# tasks file for fai-setup
- name: Setup fai on system
  import_tasks: setup-base.yml
  become: yes
  when: only_push is undefined

- name: Create root image
  when: (setup_type == "distributed") and (only_push is undefined)
  import_tasks: setup-root.yml
  become: yes

- name: Push root image to s3
  when: (setup_type == "distributed") and (only_push is undefined)
  import_tasks: push-root.yml
  become: yes

- name: Pull existing config git repo & include all files (from /srv/fai/config)
  when: (setup_type == "distributed") and (only_push is undefined)
  import_tasks: setup-config.yml
  become: yes

- name: Apply custom vars to fai config
  import_tasks: configure-config.yml
  become: yes
  when: only_push is undefined

- name: Push final config to git repository
  when: (setup_type == "distributed") and (do_not_push is undefined)
  import_tasks: push-config.yml
  become: yes

- name: Create pxe archive
  when: (setup_type == "distributed") and (do_not_push is undefined)
  import_tasks: setup-pxe.yml
  become: yes

- name: Push pxe archive to s3
  when: (setup_type == "distributed") and (do_not_push is undefined)
  import_tasks: push-pxe.yml
  become: yes