- name: Setup fai
  hosts: faitmp
  vars_files:
    - ./vars.yml
  tasks:
    - name: Setup fai on a temporary debian machine & publish root image to s3
      import_role:
        name: setup
        #when you use this on another project, name: berzdev.fai.setup
